# Generated by Django 6.0.5 on 2026-05-27 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP Fuel & Procurement"),
                            ("utility", "Utility Electricity"),
                            ("travel", "Corporate Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("normalizing", "Normalizing"),
                            ("ready", "Ready for Review"),
                            ("reviewing", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("parse_success_level", models.CharField(blank=True, max_length=20)),
                ("parse_errors", models.JSONField(default=list)),
                ("parse_warnings", models.JSONField(default=list)),
                ("row_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="app_ingestion.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "File Uploaded"),
                            ("parse", "File Parsed"),
                            ("normalize", "Record Normalized"),
                            ("approve", "Record Approved"),
                            ("reject", "Record Rejected"),
                            ("flag", "Record Flagged"),
                            ("edit", "Record Edited"),
                            ("lock", "Batch Locked for Audit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(max_length=50)),
                ("target_id", models.IntegerField()),
                ("detail", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_ingestion.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("raw_data", models.JSONField()),
                ("source_type", models.CharField(max_length=20)),
                ("flag", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="app_ingestion.ingestionbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "row_index"],
                "unique_together": {("batch", "row_index")},
            },
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("scope1", "Scope 1 — Direct"),
                            ("scope2", "Scope 2 — Electricity"),
                            ("scope3", "Scope 3 — Value Chain"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_state", models.CharField(blank=True, max_length=100)),
                ("fuel_type", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("quantity_unit", models.CharField(blank=True, max_length=20)),
                (
                    "quantity_normalized",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "quantity_normalized_unit",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "consumption_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("meter_id", models.CharField(blank=True, max_length=100)),
                ("discom", models.CharField(blank=True, max_length=100)),
                ("billing_start", models.DateField(blank=True, null=True)),
                ("billing_end", models.DateField(blank=True, null=True)),
                ("travel_type", models.CharField(blank=True, max_length=50)),
                ("origin", models.CharField(blank=True, max_length=100)),
                ("destination", models.CharField(blank=True, max_length=100)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("travel_class", models.CharField(blank=True, max_length=50)),
                ("employee_id", models.CharField(blank=True, max_length=50)),
                (
                    "emission_factor",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "emission_factor_source",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "co2e_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                ("was_edited", models.BooleanField(default=False)),
                ("edit_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="app_ingestion.organization",
                    ),
                ),
                (
                    "raw_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized",
                        to="app_ingestion.rawrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged for Query"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "normalized_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="app_ingestion.normalizedrecord",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
